global:
    ros__parameters:
        localization_type: "single_antenna" # "single_antenna" or "dual_antenna" or "fix_n_bearing"
        autodatum: "datum" # "auto", "cli", "datum"
        datum: [51.937587, 5.705458, 53.801823] # [latitude, longitude, altitude]
        transform: "earth_center" # "earth_center" or "datum"
        altitude: false

single_antenna:
    ros__parameters:
        name: "single_antenna"
        #input_topic:
        gps_topic: "/fix"
        #output_topics:
        gps_main: "gps_main"
        gps_aux: "gps_aux"
        kallman_type: 1

dual_antenna:
    ros__parameters:
        name: "dual_antenna"
        #input_topics:
        gps_main: "gps_main"
        gps_aux: "gps_aux"
        angle_gpses: 90.0

fix_n_bearing:
    ros__parameters:
        name: "fix_n_bearings"
        #input_topics:
        gps_corr: "gps_center"
        heading: "heading" # values in degree

using_enu:
    ros__parameters:
        name: "using_enu"
        #input_topics:
        gps_lock_time: 5

odom_n_path:
    ros__parameters:
        name: "odometry"

transform_pub:
    ros__parameters:
        name: "transform_pub"

cord_convert:
    ros__parameters:
        name: "cord_convert"
